#!/bin/sh
set -ex

for proto in $@; do
  protoc \
    -I . \
    -I /vendor \
    --go_out="paths=source_relative:." \
    --twirp_out="paths=source_relative:." \
    --twirp-gateway_out="paths=source_relative:." \
    $proto
done
